### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by noahmay**
The project currently has no license. Since this should be an open-source project we need to add one.

All previous contributors need to state that they agree to the license and that the license applies to their previous contributions.

### CODE REVIEW

**Comment by emilwihlander** [comment]
I agree

**Comment by nilsceberg** [comment]
I agree

**Comment by FilipLeTran** [comment]
I agree

**Comment by noahmay** [comment]
I agree

**Comment by kasperboyefrick** [comment]
I agree

**Comment by OskarDamkjaer** [comment]
I agree

**Comment by OskarDamkjaer** [comment]
Reminds me of this https://github.com/fsek/app/pull/173

**Comment by frednordell** [comment]
I agree

**Comment by Isak-Evaldsson** [comment]
I agree

**Review by emilwihlander — APPROVED** [review]

**Pull request merged**
